<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>移动端日志分析</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="/js/jquery-1.8.3.min.js"></script>
    <script src="/js/highcharts/highcharts.js"></script>
    <script src="/js/highcharts/modules/exporting.js"></script>
    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://www.letv.com/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="http://i1.letvimg.com/img/201206/29/iphonelogo.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">移动端日志分析</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">首页</a></li>
              <li><a href="#about">关于</a></li>
            </ul>
            <p class="navbar-text pull-right"><a href="#">username</a></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
             {{include file='Loganalysis/left_menu.phtml'}}
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <div>
            <ul class="breadcrumb">
              <li>
                <a href="#">首页</a> <span class="divider">/</span>
              </li>
              <li>
                <a href="#">库</a> <span class="divider">/</span>
              </li>
              <li class="active">数据</li>
            </ul>
          </div>
          <div class="row-fluid">
            
            <!--Step:2 Prepare a dom for ECharts which (must) has size (width & hight)-->
            <!--Step:2 为ECharts准备一个具备大小（宽高）的Dom-->
            <div id="container" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
            
                <script type="text/javascript">
                  $(function () {
                          $('#container').highcharts({
                              title: {
                                  text: 'Monthly Average Temperature',
                                  x: -20 //center
                              },
                              subtitle: {
                                  text: 'Source: WorldClimate.com',
                                  x: -20
                              },
                              xAxis: {
                                  categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                              },
                              yAxis: {
                                  title: {
                                      text: 'Temperature (°C)'
                                  },
                                  plotLines: [{
                                      value: 0,
                                      width: 1,
                                      color: '#808080'
                                  }]
                              },
                              tooltip: {
                                  valueSuffix: '°C'
                              },
                              legend: {
                                  layout: 'vertical',
                                  align: 'right',
                                  verticalAlign: 'middle',
                                  borderWidth: 0
                              },
                              series: [{
                                  name: 'Tokyo',
                                  data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
                              }, {
                                  name: 'New York',
                                  data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
                              }, {
                                  name: 'Berlin',
                                  data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
                              }, {
                                  name: 'London',
                                  data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
                              }]
                          });
                  });
                </script>

          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>
