<!DOCTYPE html>
<html lang="en">
{{include file='Loganalysis/header.phtml'}}

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          {{include file='Loganalysis/top_menu.phtml'}}
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
             {{include file='Loganalysis/left_menu.phtml'}}
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <div>
            {{include file='Loganalysis/path_menu.phtml'}}
          </div>

          <div class="row-fluid">
            <form action="" name="logcount" method="POST">
              <div class="controls controls-row">
                {{html_options name=ip options=$ipList selected=$params.ip class="span2"}}
                <input name="date" type="date" value="{{$params.date}}" class="span2" />
                {{html_options name=type options=$typeList selected=$params.type class="span2"}}
                {{html_options name=domain options=$domainList selected=$params.domain class="span2"}}
              </div>
              <div class="controls controls-row">
                  {{html_options name=time_range_start options=$time_rangeAry selected=$params.time_range_start class="span2"}}
                  {{html_options name=time_range_end options=$time_rangeAry selected=$params.time_range_end class="span2"}}
                  <button type="submit" class="btn span1">查看</button>
              </div>
            </form>
          </div>

          <div class="row-fluid">
            <div id="container" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
            
                <script type="text/javascript">
                $(function () {
                    $('#container').highcharts({
                        chart: {
                            plotBackgroundColor: null,
                            plotBorderWidth: null,
                            plotShadow: false
                        },
                        title: {
                            text: '{{$result.title_text}}'
                        },
                        tooltip: {
                          pointFormat: '{series.name}: <b>{point.percentage:.2f}% </b>'
                        },
                        plotOptions: {
                            pie: {
                                allowPointSelect: true,
                                cursor: 'pointer',
                                dataLabels: {
                                    enabled: true,
                                    color: '#000000',
                                    connectorColor: '#000000',
                                    format: '<b>{point.name}</b>: {point.percentage:.2f} %, {point.y}'
                                }
                            }
                        },
                        series: [{
                            type: 'pie',
                            name: '{{$result.title_text}}',
                            data: [{{$result.series}}]
                        }]
                    });
                });
                    
                </script>

          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>
      {{include file='Loganalysis/footer.phtml'}}

    </div><!--/.fluid-container-->

  </body>
</html>
