<!DOCTYPE html>
<html lang="en">
{{include file='Loganalysis/header.phtml'}}

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          {{include file='Loganalysis/top_menu.phtml'}}
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
             {{include file='Loganalysis/left_menu.phtml'}}
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <div>
            {{include file='Loganalysis/path_menu.phtml'}}
          </div>
          <div class="row-fluid">
            
            <div id="container" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
            
                <script type="text/javascript">
                $(function () {
                        $('#container').highcharts({
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: '{{$result.title_text}}'
                            },
                            subtitle: {
                                text: '{{$result.subtitle_text}}'
                            },
                            xAxis: {
                                categories: [{{$result.xAxis_categories}}]
                            },
                            yAxis: {
                                min: 0,
                                title: {
                                    text: '{{$result.yAxis_title_text}}'
                                }
                            },
                            tooltip: {
                                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                    '<td style="padding:0"><b>{point.y:.1f} {{$result.tooltip_valueSuffix}}</b></td></tr>',
                                footerFormat: '</table>',
                                shared: true,
                                useHTML: true
                            },
                            plotOptions: {
                                column: {
                                    pointPadding: 0.2,
                                    borderWidth: 0
                                }
                            },
                            series: [{{$result.series}}]
                        });
                    });
                    
                </script>

          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>
      {{include file='Loganalysis/footer.phtml'}}

    </div><!--/.fluid-container-->

  </body>
</html>
