<!DOCTYPE html>
<html lang="en">
{{include file='Loganalysis/header.phtml'}}

  <body>

    <div class="container-fluid">
      
        <div class="row-fluid">
          <div class="span12 center login-header">
            <h3>欢迎使用移动日志分析系统</h3>
          </div><!--/span-->
        </div><!--/row-->
        
        <div class="row-fluid">
          <div class="well span5 center login-box">
            <div class="alert alert-info">
              请使用您的帐号登录
            </div>
            <form class="form-horizontal" action="/loganalysis/user/login" method="post">
              <fieldset>
                <div class="input-prepend" title="Username" data-rel="tooltip">
                  <span class="add-on">
                    <i class="icon-user"></i>
                  </span>
                  <input autofocus class="input-large span10" name="username" id="username" type="text" value="" />
                </div>
                <div class="clearfix"></div>

                <div class="input-prepend" title="Password" data-rel="tooltip">
                  <span class="add-on">
                    <i class="icon-lock"></i>
                  </span>
                  <input class="input-large span10" name="password" id="password" type="password" value="" />
                </div>
                <div class="clearfix"></div>

                <div class="center span5">
                  <button type="submit" class="btn btn-primary">登陆</button>
                </div>
              </fieldset>
            </form>
          </div><!--/span-->
        </div><!--/row-->
      
    </div><!--/.fluid-container-->

  </body>
</html>
