<!DOCTYPE html>
<html lang="en">
{{include file='Loganalysis/header.phtml'}}

  <body>

    <div class="container-fluid">
      
        <div class="row-fluid">
          <div class="span12 center login-header">
            <h3>欢迎使用移动日志分析系统</h3>
          </div><!--/span-->
        </div><!--/row-->
        
        <div class="row-fluid">
          <div class="well span5 center login-box">
            <div class="alert alert-info">
              {{$result}}
            </div>
          </div><!--/span-->
        </div><!--/row-->
      
    </div><!--/.fluid-container-->

  </body>
</html>
