<!DOCTYPE html>
<html lang="en">
{{include file='Loganalysis/header.phtml'}}

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">客户端日志</a>
          <div class="nav-collapse">
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
             {{include file='Loganalysis/left_menu.phtml'}}
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <div>
            {{include file='Loganalysis/path_menu.phtml'}}
          </div>

          <div class="row-fluid">
            <form action="" name="logerror" method="GET">
              <div class="controls controls-row">
                <button type="button" class="btn span1" onclick="javascript:history.back()">返回</button>
              </div>
            </form>
          </div>

          <div class="row-fluid">    
            <div class="box span12" style="">
              <div class="box-content" style="display: block;">

                <div>
                    <table class="table table-bordered" >
                    <tbody>
                      <tr class="odd">
                        <td class="">
                          <fieldset>    
                            <legend>Detail Information</legend>      
                            {{$result}}
                          </fieldset>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                <div class="row-fluid">

                </div>
              </div>            
              </div>
            </div><!--/span-->
          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>
      {{include file='Loganalysis/footer.phtml'}}
    </div><!--/.fluid-container-->
    <script type="text/javascript">
      $('#filter').tooltip('show');
    </script>
  </body>
</html>